# Generated by Django 5.2.17 on 2026-08-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('bf', 'Burkina Faso'), ('ci', "Côte d'Ivoire"), ('ml', 'Mali'), ('gn', 'Guinée'), ('sn', 'Sénégal'), ('ne', 'Niger'), ('bj', 'Bénin'), ('cm', 'Cameroun'), ('ga', 'Gabon'), ('cd', 'République Démocratique du Congo'), ('other', 'Autre pays')], default='bf', max_length=20),
        ),
    ]
